app:
  name: rxintake
  env: dev
  port: 8080
logging:
  level: debug
  format: console
external:
  pharmacy:
    base_url: "http://localhost:9090"
    path: "api/pharmacy/prescriptions"
    use_mock: true
    api_key: ""
    timeout: "10s"
  billing:
    base_url: "http://localhost:9090"
    path: "api/billing/invoices"
    use_mock: true
    timeout: "10s"
