app:
  name: PharmacyModernization
  env: dev  # Override with RX_APP_ENV=prod to load app.prod.yaml
  port: 8080
logging:
  enabled: true  # Set to false to disable logging entirely
  level: debug
  format: console  # "console" or "json"
  output: file  # "console", "file", or "both"
  file_path: "logs/app.log"  # Path to log file (only used when output is "file" or "both")
  file_max_size: 100  # Max size in MB before rotation
  file_max_backups: 3  # Max number of old log files to keep
  file_max_age: 28  # Max days to retain old log files
database:
  mongodb:
    # REQUIRED: Set via environment variable RX_DATABASE_MONGODB_URI (UPPERCASE)
    # For local development, set in .env file
    uri: ""  # Override with RX_DATABASE_MONGODB_URI
    database: "pharmacy_modernization"
    collections:
      patients: "patients"
      addresses: "addresses"
      prescriptions: "prescriptions"
    connection:
      max_pool_size: 100
      min_pool_size: 5
      max_idle_time: "30m"
      connect_timeout: "10s"
      socket_timeout: "30s"
    options:
      retry_writes: true
      retry_reads: true
auth:
  dev_mode: true  # ONLY for local development - bypasses JWT with mock users
  jwt:
    # REQUIRED: Set via RX_AUTH_JWT_SECRET (UPPERCASE)
    # Even in dev mode, should be set for when dev_mode is disabled
    secret: ""  # Override with RX_AUTH_JWT_SECRET
    issuer: "PharmacyModernization"
    audience: "PharmacyModernization"
    cookie:
      name: "auth_token"
      secure: false  # Set to true in production (HTTPS only)
      httponly: true
      max_age: 3600  # 1 hour in seconds
cache:
  # MongoDB cache configuration (independent from main database)
  mongodb:
    # REQUIRED: Set via environment variable RX_CACHE_MONGODB_URI (UPPERCASE)
    # For local development, set in .env file
    uri: ""  # Override with RX_CACHE_MONGODB_URI
    database: "pharmacy_modernization_cache"  # Separate database for cache
    collection: "cache"
    connection:
      max_pool_size: 50
      min_pool_size: 5
      max_idle_time: "30m"
      connect_timeout: "10s"
      socket_timeout: "30s"
  
  # In-memory cache configuration (for hybrid or memory-only)
  memory:
    max_cost: 67108864  # 64MB (64<<20)
    buffer_items: 64
    metrics: true
    default_ttl: "30m"
external:
  pharmacy:
    use_mock: true
    timeout: "10s"
    endpoints:
      get_prescription: "http://localhost:8881/pharmacy/v1/prescriptions/{prescriptionID}"
  billing:
    use_mock: false
    timeout: "10s"
    endpoints:
      get_invoice: "http://localhost:8881/billing/v1/invoices/{prescriptionID}"
      get_invoices_by_patient: "http://localhost:8881/billing/v1/patients/{patientID}/invoices"
      create_invoice: "http://localhost:8881/billing/v1/invoices"
      acknowledge_invoice: "http://localhost:8881/billing/v1/invoices/{invoiceID}/acknowledge"
      get_invoice_payment: "http://localhost:8881/billing/v1/invoices/{invoiceID}/payment"
