# Production Configuration
# This file is merged with app.yaml when RX_APP_ENV=prod
# Use environment variables for sensitive values (RX_ prefix, UPPERCASE)

app:
  env: prod
  port: 8080

logging:
  level: info
  format: json
  output: both  # Log to both console and file

auth:
  dev_mode: false  # MUST be false in production
  jwt:
    cookie:
      name: "auth_token"
      secure: true  # HTTPS only
      httponly: true
      max_age: 3600
    # JWKS Configuration
    # REQUIRED: Set via RX_AUTH_JWT_JWKS_URL (UPPERCASE)
    token_types_config:
      auth_pass:
        jwks_url: "https://your-auth-provider.com/.well-known/jwks.json"
        signing_methods: ["RS256", "ES256", "RS512"]
        issuer: ["PharmacyModernization"]
        audience: ["PharmacyModernization"]
        client_ids: ["production-client", "mobile-app", "web-app"]
      azure_b2c:
        jwks_url: "https://yourtenant.b2clogin.com/yourtenant.onmicrosoft.com/B2C_1_signupsignin/discovery/v2.0/keys"
        signing_methods: ["RS256", "ES256"]
        issuer: ["https://yourtenant.b2clogin.com/yourtenant.onmicrosoft.com/v2.0/"]
        audience: ["your-app-id"]
        client_ids: ["your-client-id"]
    jwks_cache: 15  # Cache duration in minutes (default: 15)
    token_types: ["auth_pass", "azure_b2c"]  # Supported token types

database:
  mongodb:
    uri: ""  # REQUIRED: Set via RX_DATABASE_MONGODB_URI
    database: "pharmacy_modernization"
    collections:
      patients: "patients"
    connection:
      max_pool_size: 100
      min_pool_size: 10
      max_idle_time: "30m"
      connect_timeout: "10s"
      socket_timeout: "30s"
    options:
      retry_writes: true
      retry_reads: true

cache:
  mongodb:
    uri: ""  # REQUIRED: Set via RX_CACHE_MONGODB_URI
    database: "pharmacy_modernization_cache"

external:
  pharmacy:
    use_mock: false
    timeout: "10s"
    # Configure endpoints via RX_EXTERNAL_PHARMACY_ENDPOINTS_* if needed
  billing:
    use_mock: false
    timeout: "10s"
    # Configure endpoints via RX_EXTERNAL_BILLING_ENDPOINTS_* if needed

