# Production Configuration
# This file is merged with app.yaml when RX_APP_ENV=prod
# Use environment variables for sensitive values (RX_ prefix, UPPERCASE)

app:
  env: prod
  port: 8080

logging:
  level: info
  format: json
  output: both  # Log to both console and file

auth:
  dev_mode: false  # MUST be false in production
  jwt:
    secret: ""  # REQUIRED: Set via RX_AUTH_JWT_SECRET
    issuer: "PharmacyModernization"
    audience: "PharmacyModernization"
    cookie:
      name: "auth_token"
      secure: true  # HTTPS only
      httponly: true
      max_age: 3600

database:
  mongodb:
    uri: ""  # REQUIRED: Set via RX_DATABASE_MONGODB_URI
    database: "pharmacy_modernization"
    collections:
      patients: "patients"
    connection:
      max_pool_size: 100
      min_pool_size: 10
      max_idle_time: "30m"
      connect_timeout: "10s"
      socket_timeout: "30s"
    options:
      retry_writes: true
      retry_reads: true

cache:
  mongodb:
    uri: ""  # REQUIRED: Set via RX_CACHE_MONGODB_URI
    database: "pharmacy_modernization_cache"

external:
  pharmacy:
    use_mock: false
    timeout: "10s"
    # Configure endpoints via RX_EXTERNAL_PHARMACY_ENDPOINTS_* if needed
  billing:
    use_mock: false
    timeout: "10s"
    # Configure endpoints via RX_EXTERNAL_BILLING_ENDPOINTS_* if needed

