app:
  name: rxintake
  env: dev
  port: 8080
logging:
  level: debug
  format: console
database:
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "rxintake"
    collections:
      patients: "patients"
    connection:
      max_pool_size: 100
      min_pool_size: 5
      max_idle_time: "30m"
      connect_timeout: "10s"
      socket_timeout: "30s"
    options:
      retry_writes: true
      retry_reads: true
external:
  pharmacy:
    base_url: "http://localhost:9090"
    path: "api/pharmacy/prescriptions"
    use_mock: true
    api_key: ""
    timeout: "10s"
  billing:
    base_url: "http://localhost:9090"
    path: "api/billing/invoices"
    use_mock: true
    timeout: "10s"
