version: "3.8"

# This compose file works with both Podman and Docker
# For Podman, use: podman-compose up -d
# For Docker, use: docker compose up -d

# Note: At work, change the image to your enterprise registry:
# image: docker.repo1.uhc.com/mongo:6.0

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
