version: "3.8"

# This compose file works with both Podman and Docker
# For Podman, use: podman-compose up -d
# For Docker, use: docker compose up -d

services:
  mongodb:
    image: mongo:7.0
    container_name: rxintake_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - rxintake_network

  mongo-express:
    image: mongo-express:latest
    container_name: rxintake_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - rxintake_network

  redis:
    image: redis:7-alpine
    container_name: rxintake_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - rxintake_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: rxintake_redis_commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379:0:redis123
      HTTP_USER: admin
      HTTP_PASSWORD: admin123
    depends_on:
      - redis
    networks:
      - rxintake_network

  memcached:
    image: memcached:1.6-alpine
    container_name: rxintake_memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: memcached -m 64
    networks:
      - rxintake_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  rxintake_network:
    driver: bridge
