# This compose file works with both Podman and Docker
# For Podman, use: podman-compose up -d
# For Docker, use: docker compose up -d

# image: docker.repo1.uhc.com/mongo:6.0

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    command: memcached -m 64 -c 1024 -I 4m
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb_data:
